spring:
  application:
    name: stream-processor
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    streams:
      application-id: upbit-stream-processor
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        commit.interval.ms: 1000

apicurio:
  registry:
    url: ${APICURIO_REGISTRY_URL:http://localhost:8080/apis/registry/v3}

server:
  port: 8082
