apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - name: api-server
          image: upbit-price-stream-api-server:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: upbit-kafka-kafka-bootstrap:9092
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 384Mi
              cpu: 500m
