apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: upbit-price-stream
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ShinSungRok/upbit-price-stream.git
    targetRevision: main
    path: charts/upbit-price-stream
  destination:
    server: https://kubernetes.default.svc
    namespace: upbit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m
