apiVersion: v1
kind: Service
metadata:
  name: history-api
spec:
  type: ClusterIP
  selector:
    app: history-api
  ports:
    - port: {{ .Values.historyApi.service.port }}
      targetPort: {{ .Values.historyApi.service.port }}
