apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual-role
  labels:
    strimzi.io/cluster: {{ .Values.kafka.clusterName }}
spec:
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: ephemeral
        kraftMetadata: shared
  resources:
{{ toYaml .Values.kafka.resources | indent 4 }}
  jvmOptions:
    "-Xms": {{ .Values.kafka.jvmHeap | quote }}
    "-Xmx": {{ .Values.kafka.jvmHeap | quote }}
