apiVersion: v1
kind: Service
metadata:
  name: valkey
spec:
  type: ClusterIP
  selector:
    app: valkey
  ports:
    - port: {{ .Values.valkey.service.port }}
      targetPort: {{ .Values.valkey.service.port }}
