apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  labels:
    app: valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
        - name: valkey
          image: "{{ .Values.valkey.image.repository }}:{{ .Values.valkey.image.tag }}"
          ports:
            - containerPort: {{ .Values.valkey.service.port }}
          resources:
{{ toYaml .Values.valkey.resources | indent 12 }}
